# This Makefile simply invokes the generic Makefile in the stm32 folder.
# The default target ic and project name may be overwritten with command line 
# arguments.  For example,
#     >> make TARGET_IC=STM32F303XC
#     >> make TARGET_IC=STM32F37X

PROJNAME  = main
TARGET_IC = STM32F37X

include ../../../stm32/Makefile