# This Makefile simply invokes the generic Makefile in the stm32 folder.
# The default target ic and project name may be overwritten with command line 
# arguments.  For example,
#     >> make TARGET_IC=STM32F303XC
#     >> make TARGET_IC=STM32F37X

PROJNAME  = main
TARGET_IC = STM32F37X

# --------------------------------------------------------
# If you want to specify your customized library, edit the
# USER_LIB directory. If not, comment USER_LIB.
# --------------------------------------------------------

# USER_LIB = ../../../smores_common

include ../../../stm32/Makefile